# Generated by Django 5.1.4 on 2025-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastry',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='pastries/'),
        ),
    ]
