# Generated by Django 5.1.4 on 2025-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pastry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastry',
            name='category',
        ),
        migrations.AddField(
            model_name='pastry',
            name='category',
            field=models.ManyToManyField(to='app.category'),
        ),
    ]
